apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-logger
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: controller
          image: events-logger
          imagePullPolicy: Never
