apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: events-logger
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get