apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: events-logger
subjects:
  - kind: ServiceAccount
    name: events-logger
