name: Release
on: [release]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    env:
      OWNER: kaidotdev
      REPOSITORY_NAME: events-logger
      IMAGE_NAME: events-logger
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Publish
        run: |
          IMAGE_PATH=docker.pkg.github.com/${OWNER}/${REPOSITORY_NAME}/${IMAGE_NAME}
          TAG=${GITHUB_REF##*/}
          docker build -t $IMAGE_PATH:$TAG .
          docker login docker.pkg.github.com -u $OWNER -p ${{ secrets.GITHUB_TOKEN }}
          docker push $IMAGE_PATH:$TAG
